# controller.yaml
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Joint 0
position_controller_0:
  type: "effort_controllers/JointPositionController"
  joint: "0"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_0:
  type: "effort_controllers/JointVelocityController"
  joint: "0"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_0:
  type: "effort_controllers/JointEffortController"
  joint: "0"

# Joint 1
position_controller_1:
  type: "effort_controllers/JointPositionController"
  joint: "1"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_1:
  type: "effort_controllers/JointVelocityController"
  joint: "1"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_1:
  type: "effort_controllers/JointEffortController"
  joint: "1"

# Joint 2
position_controller_2:
  type: "effort_controllers/JointPositionController"
  joint: "2"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_2:
  type: "effort_controllers/JointVelocityController"
  joint: "2"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_2:
  type: "effort_controllers/JointEffortController"
  joint: "2"

# Joint 3
position_controller_3:
  type: "effort_controllers/JointPositionController"
  joint: "3"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_3:
  type: "effort_controllers/JointVelocityController"
  joint: "3"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_3:
  type: "effort_controllers/JointEffortController"
  joint: "3"

# Joint 4
position_controller_4:
  type: "effort_controllers/JointPositionController"
  joint: "4"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_4:
  type: "effort_controllers/JointVelocityController"
  joint: "4"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_4:
  type: "effort_controllers/JointEffortController"
  joint: "4"

# Joint 5
position_controller_5:
  type: "effort_controllers/JointPositionController"
  joint: "5"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_5:
  type: "effort_controllers/JointVelocityController"
  joint: "5"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_5:
  type: "effort_controllers/JointEffortController"
  joint: "5"

# Joint 6
position_controller_6:
  type: "effort_controllers/JointPositionController"
  joint: "6"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_6:
  type: "effort_controllers/JointVelocityController"
  joint: "6"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_6:
  type: "effort_controllers/JointEffortController"
  joint: "6"

# Joint 7
position_controller_7:
  type: "effort_controllers/JointPositionController"
  joint: "7"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_7:
  type: "effort_controllers/JointVelocityController"
  joint: "7"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_7:
  type: "effort_controllers/JointEffortController"
  joint: "7"

# Joint 8
position_controller_8:
  type: "effort_controllers/JointPositionController"
  joint: "8"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_8:
  type: "effort_controllers/JointVelocityController"
  joint: "8"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_8:
  type: "effort_controllers/JointEffortController"
  joint: "8"

# Joint 9
position_controller_9:
  type: "effort_controllers/JointPositionController"
  joint: "9"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_9:
  type: "effort_controllers/JointVelocityController"
  joint: "9"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_9:
  type: "effort_controllers/JointEffortController"
  joint: "9"

# Joint 10
position_controller_10:
  type: "effort_controllers/JointPositionController"
  joint: "10"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_10:
  type: "effort_controllers/JointVelocityController"
  joint: "10"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_10:
  type: "effort_controllers/JointEffortController"
  joint: "10"

# Joint 11
position_controller_11:
  type: "effort_controllers/JointPositionController"
  joint: "11"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_11:
  type: "effort_controllers/JointVelocityController"
  joint: "11"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_11:
  type: "effort_controllers/JointEffortController"
  joint: "11"

# Joint 12
position_controller_12:
  type: "effort_controllers/JointPositionController"
  joint: "12"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_12:
  type: "effort_controllers/JointVelocityController"
  joint: "12"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_12:
  type: "effort_controllers/JointEffortController"
  joint: "12"

# Joint 13
position_controller_13:
  type: "effort_controllers/JointPositionController"
  joint: "13"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_13:
  type: "effort_controllers/JointVelocityController"
  joint: "13"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_13:
  type: "effort_controllers/JointEffortController"
  joint: "13"

# Joint 14
position_controller_14:
  type: "effort_controllers/JointPositionController"
  joint: "14"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_14:
  type: "effort_controllers/JointVelocityController"
  joint: "14"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_14:
  type: "effort_controllers/JointEffortController"
  joint: "14"

# Joint 15
position_controller_15:
  type: "effort_controllers/JointPositionController"
  joint: "15"
  pid: {p: 100.0, i: 1.0, d: 0.01}

velocity_controller_15:
  type: "effort_controllers/JointVelocityController"
  joint: "15"
  pid: {p: 10.0, i: 0.5, d: 0.0}

effort_controller_15:
  type: "effort_controllers/JointEffortController"
  joint: "15"
