index_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint0
    - joint2
    - joint3
  gains:
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
middle_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint5
    - joint4
    - joint6
    - joint7
  gains:
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ring_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint9
    - joint8
    - joint10
    - joint11
  gains:
    joint9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
thumb_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint12
    - joint13
    - joint14
    - joint15
  gains:
    joint12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint15:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
leap_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint0
    - joint2
    - joint3
    - joint12
    - joint13
    - joint14
    - joint15
    - joint5
    - joint4
    - joint6
    - joint7
    - joint9
    - joint8
    - joint10
    - joint11
  gains:
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint15:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
index_v_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint0
    - joint2
    - joint3
  gains:
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
middle_v_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint5
    - joint4
    - joint6
    - joint7
  gains:
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ring_v_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint9
    - joint8
    - joint10
    - joint11
  gains:
    joint9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
thumb_v_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint12
    - joint13
    - joint14
    - joint15
  gains:
    joint12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint15:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
leap_v_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint0
    - joint2
    - joint3
    - joint12
    - joint13
    - joint14
    - joint15
    - joint5
    - joint4
    - joint6
    - joint7
    - joint9
    - joint8
    - joint10
    - joint11
  gains:
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint15:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
index_p_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint0
    - joint2
    - joint3
  gains:
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
middle_p_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint5
    - joint4
    - joint6
    - joint7
  gains:
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ring_p_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint9
    - joint8
    - joint10
    - joint11
  gains:
    joint9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
thumb_p_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint12
    - joint13
    - joint14
    - joint15
  gains:
    joint12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint15:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
leap_p_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint0
    - joint2
    - joint3
    - joint12
    - joint13
    - joint14
    - joint15
    - joint5
    - joint4
    - joint6
    - joint7
    - joint9
    - joint8
    - joint10
    - joint11
  gains:
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint15:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1