index_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - 1
    - 0
    - 2
    - 3
  gains:
    1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
index_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - 1
    - 0
    - 2
    - 3
  gains:
    1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
middle_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - 5
    - 4
    - 6
    - 7
  gains:
    5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ring_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - 9
    - 8
    - 10
    - 11
  gains:
    9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
thumb_finger_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - 12
    - 13
    - 14
    - 15
  gains:
    12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    15:
      p: 100
      d: 1
      i: 1
      i_clamp: 1