controller_list:
  - name: index_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - 1
      - 0
      - 2
      - 3
  - name: index_finger_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - 1
      - 0
      - 2
      - 3
  - name: middle_finger_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - 5
      - 4
      - 6
      - 7
  - name: ring_finger_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - 9
      - 8
      - 10
      - 11
  - name: thumb_finger_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - 12
      - 13
      - 14
      - 15